todo_project/login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
   path('login/', views.login, name='login'),
   path('logout/', views.logout, name='logout'),
   path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
   path('password_reset/', views.password_reset, name='password_reset'),
   path('sign_up/', views.sign_up, name='sign_up'),
   path('delete_account/', views.delete_account, name='delete_account'),
]

todo_project/todo_app/urls.py
from django.urls import path
from . import views

app_name = 'todo_app'

urlpatterns = [
        path('', views.index, name='index'),
        path('change_status', views.change_status, name='change_status'),
        path('completed_todo/', views.completed_todos, name='completed_todos'),
        path('delete_todo/', views.delete_todo, name='delete_todo'),
        ] 

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo_app.urls')),
    path('accounts/', include('login_app.urls')),
]

todo_project/login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe

class PasswordResetRequest(models.Model):
    # ForeignKey links the PasswordResetRequest to the user
    # -> keep track of the history of password reset attempts
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Add a strong random sequence of characters that can safely be url encoded
    token = models.CharField(max_length=43, default=token_urlsafe)

    # Set time when the object is instantiated
    # created_timestamp is set once
    created_timestamp = models.DateTimeField(auto_now_add=True)

    # updated_timestamp is to be set every time the obj is saved
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}'

todo_project/login_app/views.py
from django.conf import settings
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from . models import PasswordResetRequest
from django.contrib.auth.decorators import login_required

def login(request):
   context = {}

   if request.method == "POST":
      user = authenticate(request, username=request.POST['user'], password=request.POST['password'])
      if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse(settings.LOGIN_REDIRECT_VIEW))
      else:
            context = {
               'error': 'Bad username or password.'
            }
   return render(request, 'login_app/login.html', context)



def logout(request):
   dj_logout(request)
   return render(request, 'login_app/login.html')


def request_password_reset(request):
 # Check if the user is in the system
 if request.method == "POST":
     post_user = request.POST['username']
     user = None

     if post_user:
         try:
             user = User.objects.get(username=post_user)
         except:
             print(f"Invalid password request: {post_user}")
     else:
         post_user = request.POST['email']
         try:
             user = User.objects.get(email=post_user)
         except:
             print(f"Invalid password request: {post_user}")
     if user:
         prr = PasswordResetRequest()
         prr.user = user
         prr.save()
         print(prr)
         return HttpResponseRedirect(reverse('login_app:password_reset'))

 return render(request, 'login_app/request_password_reset.html')

def password_reset(request):
 if request.method == "POST":
     post_user = request.POST['username']
     password = request.POST['password']
     confirm_password = request.POST['confirm_password']
     token = request.POST['token']

     # Check if the passwords are matched
     if password == confirm_password:
         try:
             # Get the token from the database
             prr = PasswordResetRequest.objects.get(token=token)
             prr.save()
         except:
             print("Invalid password reset attempt.")
             return render(request, 'login_app/password_reset.html')

         user = prr.user
         user.set_password(password)
         user.save()
         return HttpResponseRedirect(reverse('login_app:login'))

 return render(request, 'login_app/password_reset.html')


def sign_up(request):
   context = {}
   if request.method == "POST":
      password = request.POST['password']
      confirm_password = request.POST['confirm_password']
      user_name = request.POST['user']
      email = request.POST['email']

      if password == confirm_password:
            if User.objects.create_user(user_name, email, password):
               return HttpResponseRedirect(reverse('login_app:login'))
            else:
               context = {
                  'error': 'Could not create user account - please try again.'
               }
      else:
            context = {
               'error': 'Passwords did not match. Please try again.'
            }
   return render(request, 'login_app/sign_up.html', context)


@login_required
def delete_account(request):
   if request.method == "POST":
      if request.POST['confirm_deletion'] == "DELETE":
            user = authenticate(request, username=request.user.username, password=request.POST['password'])
            if user:
               print(f"Deleting user {user}")
               user.delete()
               return HttpResponseRedirect(reverse('login_app:login'))
            else:
               print("fail delete")

   return render(request, 'login_app/delete_account.html')

todo_project/login_app/templates/login_app/delete_account.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Delete Account</title>
</head>
<body>
   <h1>Delete Account</h1>
   <hr />
   <form action="{% url 'login_app:delete_account'%}" method="POST">
      {% csrf_token %}
      <input type="password" name="password" placeholder="Password">
      <br />
      <input type="text" name="confirm_deletion" placeholder="TYPE DELETE">
      <br />
      <button>Submit</button>
   </form>
   <hr />
</body>
</html>

todo_project/login_app/templates/login_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Login</title>
</head>
<body>
   <h1>Login</h1>
   <a href="{% url 'login_app:sign_up' %}">Sign Up</a>
   <hr />
      <form action="{% url 'login_app:login' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="user" placeholder="User Name">
            <input type="password" name="password" placeholder="Password">
            <button>Login</button>
      </form>
   <hr />
   {% if error %}
      {{ error }}
   {% endif %}

   <a href="{% url 'login_app:request_password_reset' %}">Request Password Reset</a>
</body>
</html>

todo_project/login_app/templates/login_app/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Reset Password</title>
</head>
<body>
   <h1>Reset Password</h1>
   <hr />
   <form action="{% url 'login_app:password_reset' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="User Name">
      <br />
      <input type="password" name="password" placeholder="New Password">
      <br />
      <input type="password" name="confirm_password" placeholder="Repeat New Password">
      <br />
      <input type="text" name="token" placeholder="Token">
      <br />
      <button>Submit</button>
   </form>
   <hr />
</body>
</html>

todo_project/login_app/templates/login_app/request_password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Request Password Reset</title>
</head>
<body>
   <h1>Request Password Reset</h1>
   <hr />
      <form action="{% url 'login_app:request_password_reset' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="User Name">
            <br />
            <input type="email" name="email" placeholder="Email Address">
            <br />
            <button>Submit</button>
      </form>
   <hr />
</body>
</html>

todo_project/login_app/templates/login_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Sign Up</title>
</head>
<body>
   <h1>Sign Up</h1>
   <hr />
   <form action="{% url 'login_app:sign_up' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="user" placeholder="User Name">
      <input type="email" name="email" placeholder="Email Address">
      <input type="password" name="password" placeholder="Password">
      <input type="password" name="confirm_password" placeholder="Confirm Password">
      <button>Sign Up</button>
   </form>
   <hr />
   {% if error %}
      {{ error }}
   {% endif %}
</body>
</html>