todo_project/login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
   path('login/', views.login, name='login'),
   path('logout/', views.logout, name='logout'),
   path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
   path('password_reset/', views.password_reset, name='password_reset'),
   path('sign_up/', views.sign_up, name='sign_up'),
   path('delete_account/', views.delete_account, name='delete_account'),
]

todo_project/todo_app/urls.py
from django.urls import path
from . import views

app_name = 'todo_app'

urlpatterns = [
        path('', views.index, name='index'),
        path('change_status', views.change_status, name='change_status'),
        path('completed_todo/', views.completed_todos, name='completed_todos'),
        path('delete_todo/', views.delete_todo, name='delete_todo'),
        ] 

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo_app.urls')),
    path('accounts/', include('login_app.urls')),
]

todo_project/todo_app/models.py
# Django's user authentication system
from django.contrib.auth.models import User
# Import django's standard model
from django.db import models


class Todo(models.Model):
    # Use Django's User model
    # so multiple apps in the same Project share the same user model

    # Assign a user to the Todo model
    # user becomes a prop on the Todo model with the FK type
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Add a text field to our model
    text = models.CharField(max_length=200)

    # Add a status field to our model
    status = models.BooleanField(default=False)

    # Return a human-readble representation of the model
    # & tell the todos apart in the admin panel list view
    def __str__(self):
        return f"{self.text} - {self.status}"

todo_project/todo_app/views.py
# Get Todo model
from .models import Todo
from django.shortcuts import render, get_object_or_404

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect


# The view function is provided with a (request) object
def index(request):
    # Handle a POST request from index.html form
   if request.method == 'POST':
       # If there's a POST req., get the text field out of the (request) obj
      text = request.POST["text"]

       # Create an object instance of the Todo() class
      todo = Todo()

       # Set the text prop on the obj
      todo.user = request.user
      todo.text = text

      # Save the todo object into the database --> auto PK created
      todo.save()

      # Get a list of all the todo items in the database
      #todos = Todo.objects.all()

   # Filter the query & Show the undone todo items
   todos = Todo.objects.filter(status=False).filter(user=request.user)

   # Put the list of items into a context dictionary
   context = {
            'todos': todos
   }
   return render(request, 'todo_app/index.html', context)


@login_required
# View function for the completed todos page
def change_status(request):
   # Get PK from the (request) object, shown as the hidden input in HTML
   # To find the todo item
   pk = request.POST["pk"]

   # Get the todo item from the database with the shortcut function
   todo = get_object_or_404(Todo, pk=pk, user=request.user)

   # Check the checkbox
   if "checked" in request.POST:
      todo.status = True
   else:
      todo.status = False
   todo.save()

   # Return the user to the index view after marking todo item completed
   return HttpResponseRedirect(reverse('todo_app:index'))


@login_required
# View function for Completed todo list & Handle the request from urls.py
def completed_todos(request):
   # Filter the query & Show completed todo items
   todos = Todo.objects.filter(status=True).filter(user=request.user)
   context = {
      'todos' : todos
   }
   # Take user to the Completed todo page
   return render(request, 'todo_app/completed_todos.html', context)


@login_required
# View function for Deleted todo list
def delete_todo(request):
   # Delete on Index & Completed pages
   # Tthe referring url from META prop of the (request) obj
   print(request.META['HTTP_REFERER'])
   pk = request.POST["pk"]
   todo = get_object_or_404(Todo, pk=pk, user=request.user)
   todo.delete()

   # Get the url from META prop & redirect back to the referring page
   if request.META['HTTP_REFERER'].split('/')[-2] == 'todo':
      return HttpResponseRedirect(reverse('todo_app:index'))
   else:
       return HttpResponseRedirect(reverse('todo_app:completed_todos'))

todo_project/todo_app/templates/todo_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   {% load static %}
   <link rel="stylesheet" type="text/css" href="{% static 'todo_app/todo_app.css' %}" media="screen"/>
   <title>Todo</title>
</head>
<body>
   <h1>Todo</h1>
   <p>Welcome {{ user }} - <a href="{% url 'login_app:logout' %}">Log out</a> - <a href="{% url 'login_app:delete_account' %}">Delete Account</a></p>
      {% block content %}
      {% endblock %}
      {% block footer %}
      {% endblock %}
</body>
</html>

todo_project/todo_app/templates/todo_app/completed_todos.html
{% extends "todo_app/base.html" %}

{% block content %}
    <hr />
		<ul>
			{% for todo in todos  %}
			<li>
			<form action="{% url 'todo_app:change_status' %}" method="POST">
				{% csrf_token %}
				<input type="checkbox" name="checked" {% if todo.status %}checked{% endif %} />
				<button>Update</button>
				<input type="hidden" name="pk" value="{{ todo.pk }}">
				{{ todo.text }}
			</form>
			</li>
				{% endfor  %}
		</ul>
	<hr />
{% endblock %}

{% block footer %}
<a href="{% url 'todo_app:index' %}">Todos</a>
{% endblock %}

todo_project/todo_app/templates/todo_app/index.html
{% extends "todo_app/base.html" %}

{% block content %}
    <hr />
        <ul>
            {% for todo in todos  %}
            <li>
                <form action="{% url 'todo_app:change_status' %}" method="POST">
                    {% csrf_token %}
                    <input type="checkbox" name="checked" {% if todo.status %}checked{% endif %} />
                    <button>Update</button>
                    <button formaction="{% url 'todo_app:delete_todo' %}"\>Delete</button>
                    <input type="hidden" name="pk" value="{{ todo.pk }}">
                    {{ todo.text }}
                </form>
            </li>
            {% endfor  %}
        </ul>
        <hr />
        <form action="." method="POST">
            {% csrf_token %}
            <input type="text" name="text" placeholder="Write your todo item here!" />
            <button>Add item</button>
        </form>
    <hr />
    <a href="{% url 'todo_app:completed_todos' %}">Completed todos</a>
{% endblock %}